"""
extract_bts_map.py
Parses the BTS address_map.js and writes BTS_ADDRESS_MAP.md into the repo root.
Usage: python3 scripts/extract_bts_map.py
"""

import re, sys, os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT   = os.path.dirname(SCRIPT_DIR)

SRC = os.path.join(
    REPO_ROOT,
    "..",
    "BOSS TONE STUDIO for KATANA MkII Installer",
    "_tmp_.pkg",
    "Payload (2)",
    "BOSS TONE STUDIO for KATANA MkII.app",
    "Contents",
    "Resources",
    "html",
    "js",
    "config",
    "address_map.js",
)
OUT = os.path.join(REPO_ROOT, "BTS_ADDRESS_MAP.md")

# ── Patterns ────────────────────────────────────────────────────────────────

BLOCK_RE = re.compile(
    r"var\s+(prm_\w+)\s*=\s*\[\s*//\s*(0x[0-9A-Fa-f]+)(.*?)\];",
    re.DOTALL,
)
PARAM_RE = re.compile(
    r"""\{\s*addr\s*:\s*(0x[0-9A-Fa-f]+)\s*,\s*size\s*:\s*\S+\s*,"""
    r"""\s*ofs\s*:\s*(-?\d+)\s*,\s*init\s*:\s*(-?\d+)\s*,"""
    r"""\s*min\s*:\s*(-?\d+)\s*,\s*max\s*:\s*(-?\d+)\s*,"""
    r"""\s*name\s*:\s*'([^']*)'\s*\},?\s*//\s*(.*)"""
)
TREE_ENTRY_RE = re.compile(
    r"""\{\s*addr\s*:\s*(0x[0-9A-Fa-f]+)\s*,\s*size\s*:\s*\d+\s*,"""
    r"""\s*child\s*:\s*(\w+)\s*,\s*name\s*:\s*'([^']*)'\s*\}"""
)
TREE_BLOCK_RE = re.compile(r"address_map\s*=\s*\[(.*?)\]", re.DOTALL)

# ── Load source ──────────────────────────────────────────────────────────────

if not os.path.exists(SRC):
    print("ERROR: source not found at", SRC)
    sys.exit(1)

with open(SRC, "r", encoding="utf-8") as f:
    content = f.read()

# ── Build output ─────────────────────────────────────────────────────────────

lines = []
lines.append("# Boss Tone Studio for KATANA MkII — Address Map Reference")
lines.append("")
lines.append("> Auto-generated by `scripts/extract_bts_map.py`.")
lines.append("> Source: `BOSS TONE STUDIO for KATANA MkII Installer/.../html/js/config/address_map.js`")
lines.append("> Copyright 2018 Roland Corporation. File timestamp: 20220627_1547.")
lines.append("")
lines.append("## How to read this file")
lines.append("")
lines.append("- **Offset** — the `addr` field from the JS source; relative to the block base.")
lines.append("- **ofs**    — display offset applied by BTS UI (display value = raw + ofs).")
lines.append("- **min/max** — the *display* range (after applying ofs).")
lines.append("- **init**   — default display value.")
lines.append("- Full MIDI address = block_base_address + offset,")
lines.append("  using Roland 7-bit packing when any byte would exceed 0x7F.")
lines.append("")
lines.append("---")
lines.append("")

sections_written = 0
for m in BLOCK_RE.finditer(content):
    varname = m.group(1)
    base    = m.group(2)
    body    = m.group(3)
    params  = PARAM_RE.findall(body)
    if not params:
        continue

    heading = varname.replace("prm_prop_", "").replace("prm_", "").replace("_", " ").upper()
    lines.append("## " + heading + "  (block base = `" + base + "`)")
    lines.append("")
    lines.append("| Offset | Name | min | max | init | ofs | PRM symbol |")
    lines.append("|--------|------|-----|-----|------|-----|------------|")
    for p in params:
        offset, ofs, init, mn, mx, name, comment = p
        lines.append(
            "| `" + offset + "` | " + name.strip() + " | " + mn + " | " + mx
            + " | " + init + " | " + ofs + " | " + comment.strip() + " |"
        )
    lines.append("")
    sections_written += 1

lines.append("---")
lines.append("")
lines.append("## Top-level Address Tree")
lines.append("")
lines.append("These are the absolute base addresses the BTS app uses.")
lines.append("Add block offsets from the sections above to get full MIDI addresses.")
lines.append("")

for tm in TREE_BLOCK_RE.finditer(content):
    tbody = tm.group(1)
    entries = TREE_ENTRY_RE.findall(tbody)
    if not entries:
        continue
    lines.append("| Base address | Block variable | Name |")
    lines.append("|--------------|---------------|------|")
    for t in entries:
        addr, child, name = t
        lines.append("| `" + addr + "` | `" + child + "` | " + name + " |")
    lines.append("")

output = "\n".join(lines)
with open(OUT, "w", encoding="utf-8") as f:
    f.write(output)

print("OK — wrote", sections_written, "sections,", len(lines), "lines to", OUT)
